"""empty message

Revision ID: 7a87af7f26f3
Revises: 9687675fc3a4
Create Date: 2024-01-25 10:16:13.764701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a87af7f26f3'
down_revision = '9687675fc3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=256), nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
